### ISSUE TITLE
mimeDecode uses code that's deprecated in PHP 5.5

### ISSUE THREAD

**Issue by neokio** [stuporglue/mailreader#3]
Current release is 1.5.5 (stable), released on 2010-12-02 ... produces error: 

```
preg_replace(): The /e modifier is deprecated in line 762
```

Bummer :)

**Comment by willwoodlief** [comment]
in 2016 they released a new minor version that fixed this. No errors or warnings on php 7

**Comment by neokio** [comment]
Lol! Thanks @willwoodlief
